version: '3'

services:
  db:
    container_name: yab_testing_system.db
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    env_file:
      - ./env/backend.env
    image: postgres:12.2
    restart: always
    networks:
      - yab.network
    ports:
      - 5432:5432

networks:
  yab.network:
