# Generated by Django 3.1.7 on 2021-06-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanalysis',
            name='discrimination_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='questionanalysis',
            name='lower_27_difficult_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='questionanalysis',
            name='upper_27_difficult_index',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionanalysis',
            name='difficult_index',
            field=models.FloatField(default=0),
        ),
    ]
