# Generated by Django 3.1.7 on 2021-06-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_questiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='name',
        ),
    ]
