# Generated by Django 3.1.7 on 2022-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210608_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
